<body>
    <div id="root"></div>
    <script src="https://unpkg.com/react/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.js"></script>
    <script src="https://unpkg.com/react-error-boundary@1.2.5/dist/umd/react-error-boundary.js"></script>
    <script type="text/babel">
        const root = document.getElementById("root");

        const ErrorBoundary = ReactErrorBoundary.ErrorBoundary;

        // class ErrorBoundary extends React.Component {
        //     state = {error:null}

        //     static getDerivedStateFromError(error) {
        //         return {error}
        //     }

        //     render() {
        //         const {error} = this.state

        //         if (error) {
        //             // return <div>Oh no!</div>
        //             return <this.props.FallbackComponent error={error} />
        //         }

        //         return this.props.children
        //     }

        // }

        function ErrorFallback({ error }) {
            return (
                <div>
                    <p>Something went wrong</p>
                    <pre>{error.message}</pre>
                </div>
            );
        }

        function Bomb() {
            throw new Error("ðŸ’¥ Caboom ðŸ’¥");
        }

        function App() {
            const [explode, setExplode] = React.useState(false);

            return (
                <>
                    <div>
                        <button onClick={() => setExplode(true)}>ðŸ’£</button>
                    </div>
                    <ErrorBoundary FallbackComponent={ErrorFallback}>
                        <div>{explode ? <Bomb /> : "Push the button"}</div>
                    </ErrorBoundary>
                </>
            );
        }

        ReactDOM.render(<App />, root);
    </script>
</body>
